apiVersion: v1

version: 1.0
deprecated: false

name: jarvice
appVersion: "3.0.1"
description: JARVICE cloud platform
home: http://www.nimbix.net/
maintainers:
    - name: Nimbix, Inc.
      email: support@nimbix.net
      url: http://www.nimbix.net/
keywords:
    - JARVICE
    - HPC
    - cloud
icon: https://github.com/nimbix/jarvice-helm/raw/master/skin-default/favicon.png
sources:
   - https://github.com/nimbix/jarvice-helm

engine: gotpl
#kubeVersion: ">=1.10"
tillerVersion: ">=2.9"
