{{- if or .Values.jarvice_scheduler.enabled .Values.jarvice_k8s_scheduler.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: jarvice-jobs
{{- if empty .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
  namespace: {{ .Release.Namespace }}-jobs
{{- else }}
  namespace: {{ .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
{{- end }}
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
{{- if empty .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
    name: {{ .Release.Namespace }}-jobs
{{- else }}
    name: {{ .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
{{- end }}
spec:
  selector:
    matchLabels:
      jarvice-job: "true"
  maxUnvailable: 0
---
{{- end }}
{{- if .Values.jarvice_api.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: jarvice-builds
{{- if empty .Values.jarvice.JARVICE_BUILDS_NAMESPACE }}
  namespace: {{ .Release.Namespace }}-builds
{{- else }}
  namespace: {{ .Values.jarvice.JARVICE_BUILDS_NAMESPACE }}
{{- end }}
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
{{- if empty .Values.jarvice.JARVICE_BUILDS_NAMESPACE }}
    name: {{ .Release.Namespace }}-builds
{{- else }}
    name: {{ .Values.jarvice.JARVICE_BUILDS_NAMESPACE }}
{{- end }}
spec:
  selector:
    matchLabels:
      jarvice-build: "true"
  maxUnvailable: 0
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: jarvice-pulls
{{- if empty .Values.jarvice.JARVICE_PULLS_NAMESPACE }}
  namespace: {{ .Release.Namespace }}-pulls
{{- else }}
  namespace: {{ .Values.jarvice.JARVICE_PULLS_NAMESPACE }}
{{- end }}
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
{{- if empty .Values.jarvice.JARVICE_PULLS_NAMESPACE }}
    name: {{ .Release.Namespace }}-pulls
{{- else }}
    name: {{ .Values.jarvice.JARVICE_PULLS_NAMESPACE }}
{{- end }}
spec:
  selector:
    matchLabels:
      jarvice-pull: "true"
  maxUnvailable: 0
---
{{- end }}
