jarvice:
  imagePullSecret:
    username:
    password:
  JARVICE_LICENSE_LIC:

  # JARVICE_REMOTE_* settings are used for application synchronization
  JARVICE_REMOTE_API_URL: https://api.jarvice.com
  JARVICE_REMOTE_USER:
  JARVICE_REMOTE_APIKEY:

  JARVICE_LOCAL_REGISTRY: # jarvice-registry:5000
  JARVICE_LOCAL_REPO_BASE: jarvice

  JARVICE_SYSTEM_REGISTRY: quay.io
  JARVICE_SYSTEM_REPO_BASE: nimbix
  JARVICE_IMAGES_TAG: jarvice-testing # latest
  JARVICE_IMAGES_TAG_DEV: -k8s
  JARVICE_SYSTEM_ARCH: amd64

  #nodeSelector: # '{"jarvice.io/jarvice-system": ""}'
  nodeSelector: '{"beta.kubernetes.io/arch": "amd64"}'

  JARVICE_SYSTEM_NAMESPACE: # auto-detected, should not need to be updated
  JARVICE_JOBS_NAMESPACE: # auto-set, should not need to be updated
  settings:
    configMap: jarvice-settings
  secrets:
    secretName: jarvice-secrets

# Database server previously set up?  Set enabled to false.
# Then, set JARVICE_DBHOST, JARVICE_PORTAL_DBHOST et al below in
# the jarvice_dal env and jarvice_mc_portal env.
jarvice_db:
  enabled: true
  replicaCount: 1
  nodeSelector: # '{"jarvice.io/jarvice-db": ""}'
  image: mysql:5
  persistence:
    enabled: false
    # storageClass: "-"
    storageClass: "jarvice-db"
    accessMode: ReadWriteOnce
    size: 8Gi
  env:
    MYSQL_ROOT_PASSWORD: Pass1234
    #MYSQL_USER: nimbix # optional, alternative superuser to root
    #MYSQL_PASSWORD: Pass1234

# replicaCount change requires JARVICE_PORTAL_MEMCACHED_LOCATIONS update below.
# Memcached server previously set up?  Set enabled to false.
# Then, set JARVICE_PORTAL_MEMCACHED_LOCATIONS below in jarvice_mc_portal env.
jarvice_memcached:
  enabled: true
  replicaCount: 3
  nodeSelector: # '{"jarvice.io/jarvice-memcached": ""}'
  image: memcached:1.5
  maxItemMemory: 64
  verbosity: v
  extendedOptions: modern
  resources:
    limits:
      cpu: 250m
      memory: 512Mi

# Want to run the docker registry in JARVICE namespace?  Set enabled to true.
# Then set JARVICE_LOCAL_REGISTRY to jarvice-registry:5000 as seen above
# in the jarvice: stanza.  Set loadBalancerIP if desired.
jarvice_registry:
  enabled: false
  # external must be set to true to enable direct access from outside cluster.
  external: false
  loadBalancerIP:
  replicaCount: 1
  nodeSelector: # '{"jarvice.io/jarvice-registry": ""}'
  image: registry:2
  persistence:
    enabled: false
    # storageClass: "-"
    storageClass: "jarvice-registry"
    accessMode: ReadWriteOnce
    size: 10Gi
  env:
    REGISTRY_HTTP_ADDR: 0.0.0.0:5000
    REGISTRY_HTTP_TLS_CERTIFICATE: /etc/ssl/docker/tls.crt
    REGISTRY_HTTP_TLS_KEY: /etc/ssl/docker/tls.key
  tls:
    createConfigMap: true
    configMap: jarvice-registry-tls
    data:
      tls.crt: |
        -----BEGIN CERTIFICATE-----
        MIIDpTCCAo2gAwIBAgIJAL243I/6MhAPMA0GCSqGSIb3DQEBCwUAMGkxCzAJBgNV
        BAYTAlVTMQ4wDAYDVQQIDAVUZXhhczEPMA0GA1UEBwwGRGFsbGFzMQ8wDQYDVQQK
        DAZOaW1iaXgxDzANBgNVBAsMBlBPUlRBTDEXMBUGA1UEAwwOSkFSVklDRS1QT1JU
        QUwwHhcNMTcwMzIyMDYxNjU4WhcNMTcwNDIxMDYxNjU4WjBpMQswCQYDVQQGEwJV
        UzEOMAwGA1UECAwFVGV4YXMxDzANBgNVBAcMBkRhbGxhczEPMA0GA1UECgwGTmlt
        Yml4MQ8wDQYDVQQLDAZQT1JUQUwxFzAVBgNVBAMMDkpBUlZJQ0UtUE9SVEFMMIIB
        IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwodSLyiI6uDYYbvn4pnRFcSI
        ghpQ53ezTeq23qL5f4dhTZOgR9GvcefuK1vwFxPb3bYPvn8m85Pg4vR3533F3tKV
        ERDPa7yidFefuFuSFm2PKeZJ1zTWRnDwuLKJuqtPt9OkYmvcA+SoxxPwEAkHGMDQ
        laHKsSgFa/khmNZ/OPVYJYGJ9E+nJjspoHdGauEaoRw3mXPYL+n5am5LBjEaHjRv
        J66S4TKE0m6kAhu1uvZDJF5CIwJIZQ3yo9cZaP1eTVaC3r9y/uyihTDtVUrZMJG7
        cUi26Ho4cKaRUx87EOlrrs+G/5RIOx+KpoiznaQqc7hNXf8rJH7cqvoUbeULgwID
        AQABo1AwTjAdBgNVHQ4EFgQUXxnFQMmadPSMa0oaR+Jy6qt5LZgwHwYDVR0jBBgw
        FoAUXxnFQMmadPSMa0oaR+Jy6qt5LZgwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0B
        AQsFAAOCAQEAoICYXpTUGtpiZW/VyhIz5nhzvz/ttqwXCmJ/afG7mOzjvVG45vb+
        owCKM8iNSuad8uygmbz/HnYOq+W5BJlYA/0Fvrx4OXiwyV1IhqErg1PjEbqTRHo/
        9IBK91ng62DqJBrj8NFvUqbofhTcHo7pSVKZlkuUB+cuVUPH6HRHqbtu/GYAnyUG
        xGY+Jk/4vWzJil2+DCT2JG8xKpllwhNpgWahZT8pAVBMa79zXQMj8JsdW7T1YWpg
        ZEU4n6EhkaOjENd8aHVLmzCU7Z1zmcPRL6/4E2tPKVIEhkmd8x3hteN77pS3ZHdZ
        1+F4fuWkwQw0vJAI9MvxbOn6I3d8en1nJA==
        -----END CERTIFICATE-----
      tls.key: |
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDCh1IvKIjq4Nhh
        u+fimdEVxIiCGlDnd7NN6rbeovl/h2FNk6BH0a9x5+4rW/AXE9vdtg++fybzk+Di
        9HfnfcXe0pUREM9rvKJ0V5+4W5IWbY8p5knXNNZGcPC4som6q0+306Ria9wD5KjH
        E/AQCQcYwNCVocqxKAVr+SGY1n849VglgYn0T6cmOymgd0Zq4RqhHDeZc9gv6flq
        bksGMRoeNG8nrpLhMoTSbqQCG7W69kMkXkIjAkhlDfKj1xlo/V5NVoLev3L+7KKF
        MO1VStkwkbtxSLboejhwppFTHzsQ6Wuuz4b/lEg7H4qmiLOdpCpzuE1d/yskftyq
        +hRt5QuDAgMBAAECggEAErb0GCddLMOe7aAnSeykaeSzgVjIycwBSxC2sSqauEMt
        AEqgk+g/acT3a+J3cbDuaSEX2Krg83QZoZwFYRb/j1VRFAg6/FF0i57WdeURY+j8
        afqGxhaGOtaowgwjJftPOw84dGOOEi3Qcv6fDNvhe+co6gxbtLl19BJOwiZ4rOD6
        jFRncSvYxrR5+6aqhV4IOFgxhYwXFehlf0kU3OqM6cIvTDI8nhqrZadtyqL3eiWx
        2UsGBGNRdXydURcXMMm9jUhF8SkTSiXlclGD+If5pEP1+CqhD/Pn3MmIHy4hBAcS
        Gl/5+dB9oqybrSPfJpSR7Ga+yq7rQl/8CVGrHqAc+QKBgQD1kncbWJUsvU+B/WBd
        tLbEpb3jk0qCrH1UQKqZpunaC+pAJe1/y/WzFnxqz1EqRdM1mVQPMSggZkvEdgI/
        6e4Rz9TAkKcMjxiuJZE09xyaJ2b4JRw7OMXgav/XSy8OdBLfBFDxUFfdCibY7bpz
        +pnZqfPJIKPshNhXWTCcmG3idQKBgQDKyfpnPGGupKMHfq7gwImGfKFzLUcR81ix
        W1uAFKI/cynxW0Lt9U/sPA4Ep+YwyYCaB2k8wP5W5jDfDm3UQ3UyoBuDJndkZcqh
        5pa8OSc3Bv2aZ8zF9zUFcttFMCpPMyVQOyidU4lC6B7OUQC/HGnAhybt/gcopUjL
        BaDY+/KHFwKBgFc9Sxbp50TXlBFH5B4l/u/pOYZJYyT9BiESQAkJ5PXTWcqkLrVB
        ze1rRZPkRp9P4vKdn+Etw2WPMcd/bNkrz6mAPcKTIOUzSL9FFUrNptmUud3ZwSfA
        yXsqR+1CBluKHNIhhGfV9QDPhHF4Ms7U7icHW1XORK3Xm8ucIcrf09mpAoGBAJhH
        NabiO8QGU3okUjPpwRvhaOdxf6XmI5sDLGGwnOmilENusYK5LKwLqMcsQXovRkfj
        +s2paxRcRSSq1CSKB27dtes1LoCQw6nx2w06qczzjeqtuaKK8SDHUArTkWHp2UI3
        OldxzGgWoFNzlmjscCkoFD6w/DU0cMYr0s4927A/AoGAAb16SNEPFBmXzAxfQ1dd
        YtkjDqhjr0rPBPmPjXdzNzNFrhPOeGktA7iyhec52wqvXzMVAC6CV0p7XGdiNuI7
        szrFxPpObl3oyzaeT7/vWKsLoJK1wLbzJSDOWpSoLbiLUhuJFxlnsgO31ScpOXLN
        P6mgO0ziUxnWqWCcPC7y85M=
        -----END PRIVATE KEY-----

jarvice_dal:
  enabled: true
  replicaCount: 2
  resources:
    limits:
      cpu: 1
      memory: 16Gi
  hostNetwork: false
  nodeSelector: # '{"jarvice.io/jarvice-dal": ""}'
  # jarvice.settings.configMap takes precedence over envornment settings
  # for JARVICE_CFG_NETWORK
  # JARVICE_SITE_DBPASSWD inherits from jarvice_db.MYSQL_ROOT_PASSWORD if unset
  env:
    JARVICE_SITE_DBHOST: jarvice-db
    JARVICE_SITE_DBUSER: root
    JARVICE_SITE_DBPASSWD: # Pass1234
    JARVICE_ROOT_USER_CREATE: False
    JARVICE_ROOT_USER_PASSWD: Pass1234
    JARVICE_ROOT_USER_EMAIL: root@localhost
    JARVICE_USER_REGISTRY_VERIFY: False
    JARVICE_ROOT_USER_VAULT: # default-BLOCK-1GB
    JARVICE_ROOT_USER_VAULT_SIZE: # 1
    JARVICE_CFG_NETWORK: |
        [global]
        netmask: 255.255.0.0
        gateway: 172.17.0.1
        dns: 8.8.8.8,8.8.4.4
        search: localdomain,dev.nimbix.net,nimbix.net
        linuxbr: docker0
        naelimit: 10
        nae_nfs_bind: 172.17.0.0/16
        [floating]
        start: 172.17.0.100
        end: 172.17.0.255
        [nat]
        [static]
        [fqdns]
        [naelimits]

jarvice_scheduler:
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 1
      memory: 4Gi
  nodeSelector: # '{"jarvice.io/jarvice-scheduler": ""}'
  # jarvice.settings.configMap takes precedence over envornment settings
  # for JARVICE_MAIL_CONF
  env:
    JARVICE_USE_LXCFS: yes
    JARVICE_K8S_ADMIN_CONF:
    JARVICE_SCHED_PASS_INTERVAL: 5
    JARVICE_MAIL_CONF: |
        [mail]
        from: JARVICE Job Status <DoNotReply@localhost>
        admins: root@localhost
        [smtp]
        server: localhost:25
        ;username: DoNotReply@localhost
        ;password: Pass1234

jarvice_api:
  enabled: true
  replicaCount: 2
  loadBalancerIP:
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
  nodeSelector: # '{"jarvice.io/jarvice-api": ""}'

jarvice_dockerpull:
  nodeSelector: # '{"jarvice.io/jarvice-dockerpull": ""}'


jarvice_appsync:
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
  nodeSelector: # '{"jarvice.io/jarvice-appsync": ""}'
  env:
    JARVICE_SYSTEM_REGISTRY: quay.io
    JARVICE_SYSTEM_REPO_BASE: nimbix
    JARVICE_APPSYNC_INTERVAL: 3600
  livenessProbe:
    periodSeconds: 900

jarvice_mc_portal:
  enabled: true
  replicaCount: 2
  loadBalancerIP:
  resources:
    limits:
      cpu: 250m
      memory: 2Gi
  nodeSelector: # '{"jarvice.io/jarvice-mc-portal": ""}'
  # jarvice.settings.configMap takes precedence over envornment settings
  # for JARVICE_MC_PORTAL_CRT and JARVICE_MC_PORTAL_KEY
  # JARVICE_PORTAL_DBPASSWD inherits from jarvice_db.MYSQL_ROOT_PASSWORD if unset
  env:
    JARVICE_MC_PORTAL_CRT: |
        -----BEGIN CERTIFICATE-----
        MIIDpTCCAo2gAwIBAgIJAL243I/6MhAPMA0GCSqGSIb3DQEBCwUAMGkxCzAJBgNV
        BAYTAlVTMQ4wDAYDVQQIDAVUZXhhczEPMA0GA1UEBwwGRGFsbGFzMQ8wDQYDVQQK
        DAZOaW1iaXgxDzANBgNVBAsMBlBPUlRBTDEXMBUGA1UEAwwOSkFSVklDRS1QT1JU
        QUwwHhcNMTcwMzIyMDYxNjU4WhcNMTcwNDIxMDYxNjU4WjBpMQswCQYDVQQGEwJV
        UzEOMAwGA1UECAwFVGV4YXMxDzANBgNVBAcMBkRhbGxhczEPMA0GA1UECgwGTmlt
        Yml4MQ8wDQYDVQQLDAZQT1JUQUwxFzAVBgNVBAMMDkpBUlZJQ0UtUE9SVEFMMIIB
        IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwodSLyiI6uDYYbvn4pnRFcSI
        ghpQ53ezTeq23qL5f4dhTZOgR9GvcefuK1vwFxPb3bYPvn8m85Pg4vR3533F3tKV
        ERDPa7yidFefuFuSFm2PKeZJ1zTWRnDwuLKJuqtPt9OkYmvcA+SoxxPwEAkHGMDQ
        laHKsSgFa/khmNZ/OPVYJYGJ9E+nJjspoHdGauEaoRw3mXPYL+n5am5LBjEaHjRv
        J66S4TKE0m6kAhu1uvZDJF5CIwJIZQ3yo9cZaP1eTVaC3r9y/uyihTDtVUrZMJG7
        cUi26Ho4cKaRUx87EOlrrs+G/5RIOx+KpoiznaQqc7hNXf8rJH7cqvoUbeULgwID
        AQABo1AwTjAdBgNVHQ4EFgQUXxnFQMmadPSMa0oaR+Jy6qt5LZgwHwYDVR0jBBgw
        FoAUXxnFQMmadPSMa0oaR+Jy6qt5LZgwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0B
        AQsFAAOCAQEAoICYXpTUGtpiZW/VyhIz5nhzvz/ttqwXCmJ/afG7mOzjvVG45vb+
        owCKM8iNSuad8uygmbz/HnYOq+W5BJlYA/0Fvrx4OXiwyV1IhqErg1PjEbqTRHo/
        9IBK91ng62DqJBrj8NFvUqbofhTcHo7pSVKZlkuUB+cuVUPH6HRHqbtu/GYAnyUG
        xGY+Jk/4vWzJil2+DCT2JG8xKpllwhNpgWahZT8pAVBMa79zXQMj8JsdW7T1YWpg
        ZEU4n6EhkaOjENd8aHVLmzCU7Z1zmcPRL6/4E2tPKVIEhkmd8x3hteN77pS3ZHdZ
        1+F4fuWkwQw0vJAI9MvxbOn6I3d8en1nJA==
        -----END CERTIFICATE-----
    JARVICE_MC_PORTAL_KEY: |
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDCh1IvKIjq4Nhh
        u+fimdEVxIiCGlDnd7NN6rbeovl/h2FNk6BH0a9x5+4rW/AXE9vdtg++fybzk+Di
        9HfnfcXe0pUREM9rvKJ0V5+4W5IWbY8p5knXNNZGcPC4som6q0+306Ria9wD5KjH
        E/AQCQcYwNCVocqxKAVr+SGY1n849VglgYn0T6cmOymgd0Zq4RqhHDeZc9gv6flq
        bksGMRoeNG8nrpLhMoTSbqQCG7W69kMkXkIjAkhlDfKj1xlo/V5NVoLev3L+7KKF
        MO1VStkwkbtxSLboejhwppFTHzsQ6Wuuz4b/lEg7H4qmiLOdpCpzuE1d/yskftyq
        +hRt5QuDAgMBAAECggEAErb0GCddLMOe7aAnSeykaeSzgVjIycwBSxC2sSqauEMt
        AEqgk+g/acT3a+J3cbDuaSEX2Krg83QZoZwFYRb/j1VRFAg6/FF0i57WdeURY+j8
        afqGxhaGOtaowgwjJftPOw84dGOOEi3Qcv6fDNvhe+co6gxbtLl19BJOwiZ4rOD6
        jFRncSvYxrR5+6aqhV4IOFgxhYwXFehlf0kU3OqM6cIvTDI8nhqrZadtyqL3eiWx
        2UsGBGNRdXydURcXMMm9jUhF8SkTSiXlclGD+If5pEP1+CqhD/Pn3MmIHy4hBAcS
        Gl/5+dB9oqybrSPfJpSR7Ga+yq7rQl/8CVGrHqAc+QKBgQD1kncbWJUsvU+B/WBd
        tLbEpb3jk0qCrH1UQKqZpunaC+pAJe1/y/WzFnxqz1EqRdM1mVQPMSggZkvEdgI/
        6e4Rz9TAkKcMjxiuJZE09xyaJ2b4JRw7OMXgav/XSy8OdBLfBFDxUFfdCibY7bpz
        +pnZqfPJIKPshNhXWTCcmG3idQKBgQDKyfpnPGGupKMHfq7gwImGfKFzLUcR81ix
        W1uAFKI/cynxW0Lt9U/sPA4Ep+YwyYCaB2k8wP5W5jDfDm3UQ3UyoBuDJndkZcqh
        5pa8OSc3Bv2aZ8zF9zUFcttFMCpPMyVQOyidU4lC6B7OUQC/HGnAhybt/gcopUjL
        BaDY+/KHFwKBgFc9Sxbp50TXlBFH5B4l/u/pOYZJYyT9BiESQAkJ5PXTWcqkLrVB
        ze1rRZPkRp9P4vKdn+Etw2WPMcd/bNkrz6mAPcKTIOUzSL9FFUrNptmUud3ZwSfA
        yXsqR+1CBluKHNIhhGfV9QDPhHF4Ms7U7icHW1XORK3Xm8ucIcrf09mpAoGBAJhH
        NabiO8QGU3okUjPpwRvhaOdxf6XmI5sDLGGwnOmilENusYK5LKwLqMcsQXovRkfj
        +s2paxRcRSSq1CSKB27dtes1LoCQw6nx2w06qczzjeqtuaKK8SDHUArTkWHp2UI3
        OldxzGgWoFNzlmjscCkoFD6w/DU0cMYr0s4927A/AoGAAb16SNEPFBmXzAxfQ1dd
        YtkjDqhjr0rPBPmPjXdzNzNFrhPOeGktA7iyhec52wqvXzMVAC6CV0p7XGdiNuI7
        szrFxPpObl3oyzaeT7/vWKsLoJK1wLbzJSDOWpSoLbiLUhuJFxlnsgO31ScpOXLN
        P6mgO0ziUxnWqWCcPC7y85M=
        -----END PRIVATE KEY-----
    JARVICE_USER_DEFAULT_ENABLED: True
    JARVICE_USER_DEFAULT_DEVELOPER: True
    JARVICE_PORTAL_MEMCACHED_LOCATIONS: jarvice-memcached-0.jarvice-memcached:11211,jarvice-memcached-1.jarvice-memcached:11211,jarvice-memcached-2.jarvice-memcached:11211
    JARVICE_PORTAL_APP_OWNERS:
    JARVICE_PORTAL_MAIL_FROM: "JARVICE Account Status <DoNotReply@localhost>"
    JARVICE_PORTAL_MAIL_SUBJECT: "Your JARVICE Account"
    JARVICE_PORTAL_MAIL_SERVER: localhost:25
    JARVICE_PORTAL_MAIL_USERNAME:
    JARVICE_PORTAL_MAIL_PASSWORD:
    JARVICE_PORTAL_MAIL_ADMINS:
    JARVICE_PORTAL_DBHOST: jarvice-db
    JARVICE_PORTAL_DBUSER: root
    JARVICE_PORTAL_DBPASSWD: # Pass1234

