apiVersion: v1
kind: PersistentVolume
metadata:
  name: jarvice-registry-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jarvice-registry
#  mountOptions:
#    - hard
#    - nfsvers=4.1
  nfs:
    path: /home/jarvice-registry
    server: 10.20.0.144
