apiVersion: v1
kind: Secret
metadata:
  name: jarvice-docker
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.jarvice.JARVICE_SYSTEM_REGISTRY (printf "%s:%s" .Values.jarvice.imagePullSecret.username .Values.jarvice.imagePullSecret.password | b64enc) | b64enc }}
