{{- if .Values.jarvice_scheduler.enabled }}
apiVersion: v1
kind: Namespace
metadata:
{{- if empty .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
  name: {{ .Release.Namespace }}-jobs
{{- else }}
  name: {{ .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
{{- end }}
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
{{- end }}
