{{- if .Values.jarvice_scheduler.enabled }}
apiVersion: v1
kind: Namespace
metadata:
{{- if empty .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
  name: {{ .Release.Namespace }}-jobs
{{- else }}
  name: {{ .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
{{- end }}
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
{{- if empty .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
    name: {{ .Release.Namespace }}-jobs
{{- else }}
    name: {{ .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
{{- end }}
---
{{- end }}
{{- if (not (eq "downstream" .Values.jarvice.JARVICE_CLUSTER_TYPE)) }}
{{- if .Values.jarvice_api.enabled }}
apiVersion: v1
kind: Namespace
metadata:
{{- if empty .Values.jarvice.JARVICE_BUILDS_NAMESPACE }}
  name: {{ .Release.Namespace }}-builds
{{- else }}
  name: {{ .Values.jarvice.JARVICE_BUILDS_NAMESPACE }}
{{- end }}
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
{{- if empty .Values.jarvice.JARVICE_BUILDS_NAMESPACE }}
    name: {{ .Release.Namespace }}-builds
{{- else }}
    name: {{ .Values.jarvice.JARVICE_BUILDS_NAMESPACE }}
{{- end }}
---
apiVersion: v1
kind: Namespace
metadata:
{{- if empty .Values.jarvice.JARVICE_PULLS_NAMESPACE }}
  name: {{ .Release.Namespace }}-pulls
{{- else }}
  name: {{ .Values.jarvice.JARVICE_PULLS_NAMESPACE }}
{{- end }}
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
{{- if empty .Values.jarvice.JARVICE_PULLS_NAMESPACE }}
    name: {{ .Release.Namespace }}-pulls
{{- else }}
    name: {{ .Values.jarvice.JARVICE_PULLS_NAMESPACE }}
{{- end }}
---
{{- end }}
{{- end }}
{{- if or .Values.jarvice.daemonsets.cache_pull.enabled .Values.jarvice.daemonsets.lxcfs.enabled .Values.jarvice.daemonsets.nvidia.enabled .Values.jarvice.daemonsets.xilinx_fpga.enabled .Values.jarvice.daemonsets.rdma.enabled }}
apiVersion: v1
kind: Namespace
metadata:
{{- if empty .Values.jarvice.JARVICE_DAEMONSETS_NAMESPACE }}
  name: {{ .Release.Namespace }}-daemonsets
{{- else }}
  name: {{ .Values.jarvice.JARVICE_DAEMONSETS_NAMESPACE }}
{{- end }}
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
{{- if empty .Values.jarvice.JARVICE_DAEMONSETS_NAMESPACE }}
    name: {{ .Release.Namespace }}-daemonsets
{{- else }}
    name: {{ .Values.jarvice.JARVICE_DAEMONSETS_NAMESPACE }}
{{- end }}
---
{{- end }}
