{{- if .Values.jarvice_api.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: jarvice-api
spec:
  selector:
    matchLabels:
      deployment: jarvice-api
  minAvailable: {{ .Values.jarvice_api.pdb.minAvailable }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvice-api
spec:
  replicas: {{ .Values.jarvice_api.replicaCount }}
  selector:
    matchLabels:
      deployment: jarvice-api
  template:
    metadata:
      labels:
        {{- include "jarvice.release_labels" . | indent 8 }}
        component: jarvice-api
        deployment: jarvice-api
      annotations:
        deployment-date: {{ now | quote }}
    spec:
      serviceAccountName: jarvice-system
{{- if (not (empty .Values.jarvice_api.tolerations)) }}
      tolerations: {{ .Values.jarvice_api.tolerations }}
{{- else if (not (empty .Values.jarvice.tolerations)) }}
      tolerations: {{ .Values.jarvice.tolerations }}
{{- end }}
{{- if (not (empty .Values.jarvice_api.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice_api.nodeSelector }}
{{- else if (not (empty .Values.jarvice.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice.nodeSelector }}
{{- end }}
      affinity:
        podAntiAffinity:
        {{- if eq .Values.jarvice_api.antiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                deployment: jarvice-api
        {{- else if eq .Values.jarvice_api.antiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  deployment: jarvice-api
        {{- end }}
      imagePullSecrets:
      - name: jarvice-docker
      containers:
      - name: jarvice-api
        image: {{ .Values.jarvice.JARVICE_SYSTEM_REGISTRY }}/{{ .Values.jarvice.JARVICE_SYSTEM_REPO_BASE }}/jarvice-api:{{ .Values.jarvice.JARVICE_IMAGES_TAG }}-{{ .Values.jarvice.JARVICE_SYSTEM_ARCH }}
        imagePullPolicy: Always
        ports:
          - name: https
            containerPort: 7443
          - name: http
            containerPort: 7080
        readinessProbe:
          httpGet:
            scheme: HTTPS
            port: https
            path: /ready
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            scheme: HTTPS
            port: https
            path: /live
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        env:
          - name: JARVICE_SYSTEM_K8S
            value: "true"
          - name: JARVICE_API_HTTPS
            value: "enable"
          - name: JARVICE_API_HTTPS_PORT
            value: "7443"
          - name: JARVICE_API_HTTP
            value: "enable"
          - name: JARVICE_API_HTTP_PORT
            value: "7080"
          - name: JARVICE_DAL_URL
{{- if empty .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
            value: "https://jarvice-dal.{{ .Release.Namespace }}:8443"
{{- else }}
            value: "https://jarvice-dal.{{ .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}:8443"
{{- end }}
          - name: JARVICE_API_URL
{{- if empty .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
            value: "https://jarvice-api.{{ .Release.Namespace }}:7443"
{{- else }}
            value: "https://jarvice-api.{{ .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}:7443"
{{- end }}
          - name: JARVICE_SCHED_URL
            value: "https://jarvice-scheduler:9443"
          - name: JARVICE_API_CRT
            valueFrom:
              secretKeyRef:
                name: jarvice-tls
                key: tls.crt
          - name: JARVICE_API_KEY
            valueFrom:
              secretKeyRef:
                name: jarvice-tls
                key: tls.key
          - name: JARVICE_JOBS_NAMESPACE
{{- if empty .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
            value: {{ .Release.Namespace }}-jobs
{{- else }}
            value: {{ .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
{{- end }}
          - name: JARVICE_BUILDS_NAMESPACE
{{- if empty .Values.jarvice.JARVICE_BUILDS_NAMESPACE }}
            value: {{ .Release.Namespace }}-builds
{{- else }}
            value: {{ .Values.jarvice.JARVICE_BUILDS_NAMESPACE }}
{{- end }}
          - name: JARVICE_PULLS_NAMESPACE
{{- if empty .Values.jarvice.JARVICE_PULLS_NAMESPACE }}
            value: {{ .Release.Namespace }}-pulls
{{- else }}
            value: {{ .Values.jarvice.JARVICE_PULLS_NAMESPACE }}
{{- end }}
          - name: JARVICE_SYSTEM_NAMESPACE
{{- if empty .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
            value: {{ .Release.Namespace }}
{{- else }}
            value: {{ .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
{{- end }}
          - name: JARVICE_SYSTEM_REGISTRY
            value: {{ .Values.jarvice.JARVICE_SYSTEM_REGISTRY }}
          - name: JARVICE_SYSTEM_REPO_BASE
            value: {{ .Values.jarvice.JARVICE_SYSTEM_REPO_BASE }}
          - name: JARVICE_IMAGES_TAG
            value: {{ .Values.jarvice.JARVICE_IMAGES_TAG }}-{{ .Values.jarvice.JARVICE_SYSTEM_ARCH }}
          - name: JARVICE_LOCAL_REGISTRY
            value: {{ .Values.jarvice.JARVICE_LOCAL_REGISTRY }}
          - name: JARVICE_LOCAL_REPO_BASE
            value: {{ .Values.jarvice.JARVICE_LOCAL_REPO_BASE }}
{{- if (not (empty .Values.jarvice_dockerbuild.tolerations)) }}
          - name: JARVICE_BUILD_NODE_TOLERATIONS
            value: '{{ .Values.jarvice_dockerbuild.tolerations }}'
{{- else if (not (empty .Values.jarvice.tolerations)) }}
          - name: JARVICE_BUILD_NODE_TOLERATIONS
            value: '{{ .Values.jarvice.tolerations }}'
{{- end }}
{{- if (not (empty .Values.jarvice_dockerpull.tolerations)) }}
          - name: JARVICE_PULL_NODE_TOLERATIONS
            value: '{{ .Values.jarvice_dockerpull.tolerations }}'
{{- else if (not (empty .Values.jarvice.tolerations)) }}
          - name: JARVICE_PULL_NODE_TOLERATIONS
            value: '{{ .Values.jarvice.tolerations }}'
{{- end }}
{{- if (not (empty .Values.jarvice_dockerbuild.nodeSelector)) }}
          - name: JARVICE_BUILD_NODE_SELECTOR
            value: '{{ .Values.jarvice_dockerbuild.nodeSelector }}'
{{- else if (not (empty .Values.jarvice.nodeSelector)) }}
          - name: JARVICE_BUILD_NODE_SELECTOR
            value: '{{ .Values.jarvice.nodeSelector }}'
{{- end }}
{{- if (not (empty .Values.jarvice_dockerpull.nodeSelector)) }}
          - name: JARVICE_PULL_NODE_SELECTOR
            value: '{{ .Values.jarvice_dockerpull.nodeSelector }}'
{{- else if (not (empty .Values.jarvice.nodeSelector)) }}
          - name: JARVICE_PULL_NODE_SELECTOR
            value: '{{ .Values.jarvice.nodeSelector }}'
{{- end }}
          - name: JARVICE_MAIL_CONF
{{- if empty .Values.jarvice_api.env.JARVICE_MAIL_CONF }}
            value: {{ toYaml .Values.jarvice.JARVICE_MAIL_CONF | indent 12 }}
{{- else }}
            value: {{ toYaml .Values.jarvice_api.env.JARVICE_MAIL_CONF | indent 12 }}
{{- end }}
        resources:
{{ toYaml .Values.jarvice_api.resources | indent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: jarvice-api
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-api
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 7443
    targetPort: 7443
    name: https
  - protocol: TCP
    port: 7080
    targetPort: 7080
    name: http
  selector:
    deployment: jarvice-api
---
{{- if (empty .Values.jarvice_api.ingressHost) }}
apiVersion: v1
kind: Service
metadata:
  name: jarvice-api-lb
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-api
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.jarvice_api.loadBalancerIP }}
  ports:
  - protocol: TCP
    port: 443
    targetPort: 7443
    name: https
  - protocol: TCP
    port: 80
    targetPort: 7080
    name: http
  selector:
    deployment: jarvice-api
---
{{- else }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jarvice-api
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-api
spec:
  rules:
  - host: {{ .Values.jarvice_api.ingressHost }}
    http:
      paths:
      - backend:
          serviceName: jarvice-api
          servicePort: http
---
{{- end }}
{{- end }}
