{{- if .Values.jarvice_registry.enabled }}
{{- if .Values.jarvice_registry.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jarvice-registry-pvc
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-registry
spec:
  accessModes:
    - {{ .Values.jarvice_registry.persistence.accessMode }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.jarvice_registry.persistence.size }}
{{- if .Values.jarvice_registry.persistence.storageClass }}
{{- if (eq "-" .Values.jarvice_registry.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.jarvice_registry.persistence.storageClass }}"
{{- end }}
{{- end }}
---
{{- end }}
{{- if (not (empty .Values.jarvice_registry.tls.secretName)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jarvice_registry.tls.secretName }}
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-registry
type: Opaque
data:
  tls.crt: {{ .Values.jarvice_registry.tls.crt }}
  tls.key: {{ .Values.jarvice_registry.tls.key }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvice-registry
spec:
  replicas: {{ .Values.jarvice_registry.replicaCount }}
  selector:
    matchLabels:
      deployment: jarvice-registry
  template:
    metadata:
      labels:
        {{- include "jarvice.release_labels" . | indent 8 }}
        component: jarvice-registry
        deployment: jarvice-registry
    spec:
{{- if (not (empty .Values.jarvice_registry.tolerations)) }}
      tolerations: {{ .Values.jarvice_registry.tolerations }}
{{- else if (not (empty .Values.jarvice.tolerations)) }}
      tolerations: {{ .Values.jarvice.tolerations }}
{{- end }}
{{- if (not (empty .Values.jarvice_registry.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice_registry.nodeSelector }}
{{- else if (not (empty .Values.jarvice.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice.nodeSelector }}
{{- end }}
      volumes:
        - name: registry-tls-cert
          secret:
{{- if (not (empty .Values.jarvice_registry.tls.secretName)) }}
            secretName: {{ .Values.jarvice_registry.tls.secretName }}
{{- else }}
            secretName: jarvice-tls
{{- end }}
            optional: true
{{- if .Values.jarvice_registry.persistence.enabled }}
        - name: registry-data-vol
          persistentVolumeClaim:
            claimName: jarvice-registry-pvc
{{- end }}
      containers:
      - name: jarvice-registry
        image: {{ .Values.jarvice_registry.image }}
        imagePullPolicy: Always
        ports:
          - name: https
            containerPort: 443
        readinessProbe:
          tcpSocket:
            port: https
          initialDelaySeconds: 5
          timeoutSeconds: 1
        livenessProbe:
          tcpSocket:
            port: https
          initialDelaySeconds: 30
          timeoutSeconds: 5
        env:
          - name: REGISTRY_HTTP_ADDR
            value: "{{ .Values.jarvice_registry.env.REGISTRY_HTTP_ADDR }}"
          - name: REGISTRY_HTTP_TLS_CERTIFICATE
            value: /etc/ssl/docker/tls.crt
          - name: REGISTRY_HTTP_TLS_KEY
            value: /etc/ssl/docker/tls.key
        volumeMounts:
        - name: registry-tls-cert
          mountPath: /etc/ssl/docker
          readOnly: true
{{- if .Values.jarvice_registry.persistence.enabled }}
        - name: registry-data-vol
          mountPath: /var/lib/registry
{{- end }}
        resources:
{{ toYaml .Values.jarvice_registry.resources | indent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: jarvice-registry
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-registry
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
    name: https
  selector:
    deployment: jarvice-registry
---
{{- if or .Values.jarvice_registry.networkPolicy.enabled (and (eq "<nil>" (toString .Values.jarvice_registry.networkPolicy.enabled)) .Values.jarvice.networkPolicy.enabled) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jarvice-registry
spec:
  podSelector:
    matchLabels:
      deployment: jarvice-registry
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443
---
{{- end }}
{{- if (empty .Values.jarvice_registry.ingressHost) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "jarvice.name" . }}-registry-lb
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-registry
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.jarvice_registry.loadBalancerIP }}
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
    name: https
  selector:
    deployment: {{ template "jarvice.name" . }}-registry
---
{{- else }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jarvice-registry
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-registry
spec:
  rules:
  - host: {{ .Values.jarvice_registry.ingressHost }}
    http:
      paths:
      - backend:
          serviceName: jarvice-registry
          servicePort: https
---
{{- end }}
{{- end }}
