{{- if .Values.jarvice_pod_scheduler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvice-pod-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: jarvice-pod-scheduler
  template:
    metadata:
      labels:
        {{- include "jarvice.release_labels" . | indent 8 }}
        component: jarvice-pod-scheduler
        deployment: jarvice-pod-scheduler
      annotations:
        deployment-date: {{ now | quote }}
    spec:
      serviceAccountName: jarvice-system
{{- if (not (empty .Values.jarvice_pod_scheduler.tolerations)) }}
      tolerations: {{ .Values.jarvice_pod_scheduler.tolerations }}
{{- else if (not (empty .Values.jarvice.tolerations)) }}
      tolerations: {{ .Values.jarvice.tolerations }}
{{- end }}
{{- if (not (empty .Values.jarvice_pod_scheduler.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice_pod_scheduler.nodeSelector }}
{{- else if (not (empty .Values.jarvice.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice.nodeSelector }}
{{- end }}
      imagePullSecrets:
      - name: jarvice-docker
      containers:
      - name: jarvice-pod-scheduler
        image: {{ .Values.jarvice.JARVICE_SYSTEM_REGISTRY }}/{{ .Values.jarvice.JARVICE_SYSTEM_REPO_BASE }}/jarvice-scheduler:{{ .Values.jarvice.JARVICE_IMAGES_TAG }}{{- include "jarvice.version" . }}
        imagePullPolicy: Always
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /usr/bin/curl -s -k https://jarvice-scheduler:9443/live | grep -q OK
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /usr/bin/curl -s -k https://jarvice-scheduler:9443/live | grep -q OK
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        env:
          - name: JARVICE_SYSTEM_K8S
            value: "true"
          - name: JARVICE_SYSTEM_NAMESPACE
{{- if empty .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
            value: {{ .Release.Namespace }}
{{- else }}
            value: {{ .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
{{- end }}
          - name: JARVICE_POD_SCHED_NAME
{{- if empty .Values.jarvice_pod_scheduler.JARVICE_POD_SCHED_NAME }}
            value: "{{ .Release.Namespace }}"
{{- else }}
            value: "{{ .Values.jarvice_pod_scheduler.env.JARVICE_POD_SCHED_NAME }}"
{{- end }}
          - name: JARVICE_POD_SCHED_LOGLEVEL
            value: "{{ .Values.jarvice.JARVICE_POD_SCHED_LOGLEVEL }}"
        resources:
{{ toYaml .Values.jarvice_pod_scheduler.resources | indent 10 }}
{{- end }}
