{{- if .Values.jarvice_api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvice-api
spec:
  replicas: {{ .Values.jarvice_api.replicaCount }}
  selector:
    matchLabels:
      deployment: jarvice-api
  template:
    metadata:
      labels:
        {{- include "jarvice.release_labels" . | indent 8 }}
        component: jarvice-api
        deployment: jarvice-api
    spec:
      serviceAccountName: jarvice-system
      nodeSelector:
        beta.kubernetes.io/arch: "{{ .Values.jarvice.JARVICE_SYSTEM_ARCH }}"
{{- if .Values.jarvice_api.nodeSelector }}
{{ toYaml .Values.jarvice_api.nodeSelector | indent 8 }}
{{- end }}
      imagePullSecrets:
      - name: jarvice-docker
      containers:
      - name: jarvice-api
        image: {{ .Values.jarvice.JARVICE_SYSTEM_REGISTRY }}/{{ .Values.jarvice.JARVICE_SYSTEM_REPO_BASE }}/jarvice-api:{{ .Values.jarvice.JARVICE_IMAGES_TAG }}-{{ .Values.jarvice.JARVICE_SYSTEM_ARCH }}{{ .Values.jarvice.JARVICE_IMAGES_TAG_DEV }}
        imagePullPolicy: Always
        ports:
          - name: https
            containerPort: 7443
          - name: http
            containerPort: 7080
        readinessProbe:
          exec:
            command:
            - /usr/bin/curl
            - -k
            - -s
            - https://jarvice-dal:8443/status
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          exec:
            command: 
            - /usr/bin/curl
            - -k
            - -s
            - https://jarvice-dal:8443/status
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        env:
          - name: JARVICE_API_HTTPS
            value: "enable"
          - name: JARVICE_API_HTTPS_PORT
            value: "7443"
          - name: JARVICE_API_HTTP
            value: "enable"
          - name: JARVICE_API_HTTP_PORT
            value: "7080"
          - name: JARVICE_DAL_URL
            value: "https://jarvice-dal:8443"
          - name: JARVICE_SCHED_URL
            value: "https://jarvice-scheduler:9443"
          - name: JARVICE_JOBS_NAMESPACE
{{- if empty .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
            value: {{ .Release.Namespace }}-jobs
{{- else }}
            value: {{ .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
{{- end }}
          - name: JARVICE_SYSTEM_NAMESPACE
{{- if empty .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
            value: {{ .Release.Namespace }}
{{- else }}
            value: {{ .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
{{- end }}
          - name: JARVICE_SYSTEM_REGISTRY
            value: {{ .Values.jarvice.JARVICE_SYSTEM_REGISTRY }}
          - name: JARVICE_SYSTEM_REPO_BASE
            value: {{ .Values.jarvice.JARVICE_SYSTEM_REPO_BASE }}
          - name: JARVICE_IMAGES_TAG
            value: {{ .Values.jarvice.JARVICE_IMAGES_TAG }}-{{ .Values.jarvice.JARVICE_SYSTEM_ARCH }}{{ .Values.jarvice.JARVICE_IMAGES_TAG_DEV }}
          - name: JARVICE_LOCAL_REGISTRY
            value: {{ .Values.jarvice.JARVICE_LOCAL_REGISTRY }}
          - name: JARVICE_LOCAL_REPO_BASE
            value: {{ .Values.jarvice.JARVICE_LOCAL_REPO_BASE }}
          - name: JARVICE_PULL_NODE_SELECTOR
            value: {{ .Values.jarvice_api.env.JARVICE_PULL_NODE_SELECTOR }}
        resources:
{{ toYaml .Values.jarvice_api.resources | indent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: jarvice-api
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-api
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 7443
    targetPort: 7443
    name: https
  - protocol: TCP
    port: 7080
    targetPort: 7080
    name: http
  selector:
    deployment: jarvice-api
---
apiVersion: v1
kind: Service
metadata:
  name: jarvice-api-lb
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-api
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.jarvice_api.loadBalancerIP }}
  ports:
  - protocol: TCP
    port: 443
    targetPort: 7443
    name: https
  - protocol: TCP
    port: 80
    targetPort: 7080
    name: http
  selector:
    deployment: jarvice-api
---
{{- end }}
