apiVersion: v1
kind: Secret
metadata:
  name: jarvice-license
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-scheduler
type: Opaque
data:
  JARVICE_LICENSE_LIC: {{ printf "%s" .Values.jarvice.JARVICE_LICENSE_LIC | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jarvice-appsync
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-appsync
type: Opaque
data:
  JARVICE_REMOTE_USER: {{ printf "%s" .Values.jarvice.JARVICE_REMOTE_USER | b64enc }}
  JARVICE_REMOTE_APIKEY: {{ printf "%s" .Values.jarvice.JARVICE_REMOTE_APIKEY | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jarvice-tls
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
type: Opaque
data:
  tls.crt: {{ .Values.jarvice.tls.crt }}
  tls.key: {{ .Values.jarvice.tls.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jarvice-docker
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.jarvice.JARVICE_SYSTEM_REGISTRY (printf "%s:%s" .Values.jarvice.imagePullSecret.username .Values.jarvice.imagePullSecret.password | b64enc) | b64enc }}
---
{{- if .Values.jarvice_scheduler.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: jarvice-docker
{{- if empty .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
  namespace: {{ .Release.Namespace }}-jobs
{{- else }}
  namespace: {{ .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
{{- end }}
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.jarvice.JARVICE_SYSTEM_REGISTRY (printf "%s:%s" .Values.jarvice.imagePullSecret.username .Values.jarvice.imagePullSecret.password | b64enc) | b64enc }}
{{- end }}
