{{- if .Values.jarvice_db.enabled }}
{{- if .Values.jarvice_db.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jarvice-db-pvc
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-db
spec:
{{- if (not (empty .Values.jarvice_db.persistence.persistentVolumeClaim.claimName)) }}
  volumes:
    - name: jarvice-db-pvc
      persistentVolumeClaim:
        claimName: "{{ .Values.jarvice_db.persistence.persistentVolumeClaim.claimName }}"
{{- end }}
  accessModes:
    - {{ .Values.jarvice_db.persistence.accessMode }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.jarvice_db.persistence.size }}
{{- if .Values.jarvice_db.persistence.storageClass }}
{{- if (eq "-" .Values.jarvice_db.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.jarvice_db.persistence.storageClass }}"
{{- end }}
{{- end }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvice-db
spec:
  replicas: {{ .Values.jarvice_db.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      deployment: jarvice-db
  template:
    metadata:
      labels:
        {{- include "jarvice.release_labels" . | indent 8 }}
        component: jarvice-db
        deployment: jarvice-db
    spec:
{{- if (not (empty .Values.jarvice_db.tolerations)) }}
      tolerations: {{ .Values.jarvice_db.tolerations }}
{{- else if (not (empty .Values.jarvice.tolerations)) }}
      tolerations: {{ .Values.jarvice.tolerations }}
{{- end }}
{{- if (not (empty .Values.jarvice_db.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice_db.nodeSelector }}
{{- else if (not (empty .Values.jarvice.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice.nodeSelector }}
{{- end }}
      containers:
      - name: jarvice-db
        image: {{ .Values.jarvice_db.image }}
        imagePullPolicy: Always
        #command:
        #  - docker-entrypoint.sh
        #  - --ignore-db-dir=lost+found
        ports:
          - name: "jarvice-db"
            containerPort: 3306
        readinessProbe:
          tcpSocket:
            port: jarvice-db
          initialDelaySeconds: 5
          timeoutSeconds: 1
        livenessProbe:
          tcpSocket:
            port: jarvice-db
          initialDelaySeconds: 30
          timeoutSeconds: 5
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: jarvice-db
{{- if (not (empty .Values.jarvice_db.env.MYSQL_ROOT_PASSWORD)) }}
                key: MYSQL_ROOT_PASSWORD
{{- else }}
                key: JARVICE_DBPASSWD
{{- end }}
{{- if or (not (empty .Values.jarvice_db.env.MYSQL_USER)) (ne "root" .Values.jarvice.JARVICE_DBUSER) }}
          - name: MYSQL_USER
{{- if (not (empty .Values.jarvice_db.env.MYSQL_USER)) }}
            value: "{{ .Values.jarvice_db.env.MYSQL_USER }}"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_DBUSER }}"
{{- end }}
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
{{- if (not (empty .Values.jarvice_db.env.MYSQL_PASSWORD)) }}
                key: MYSQL_PASSWORD
{{- else }}
                key: JARVICE_DBPASSWD
{{- end }}
{{- end }}
{{- if .Values.jarvice_db.persistence.enabled }}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-data-vol
        resources:
{{ toYaml .Values.jarvice_db.resources | indent 10 }}
      volumes:
        - name: db-data-vol
          persistentVolumeClaim:
            claimName: jarvice-db-pvc
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: jarvice-db
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-db
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    name: jarvice-db
  selector:
    deployment: jarvice-db
---
{{- if or .Values.jarvice_db.networkPolicy.enabled (and (empty (.Values.jarvice_db.networkPolicy.enabled | toStrings)) .Values.jarvice.networkPolicy.enabled) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jarvice-db
spec:
  podSelector:
    matchLabels:
      deployment: jarvice-db
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Release.Namespace }}
    ports:
    - protocol: TCP
      port: 3306
---
{{- end }}
{{- end }}
