apiVersion: v1
kind: Secret
metadata:
  name: jarvice-license
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-scheduler
type: Opaque
data:
  JARVICE_LICENSE_LIC: {{ printf "%s" .Values.jarvice.JARVICE_LICENSE_LIC | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jarvice-appsync
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-appsync
type: Opaque
data:
  JARVICE_REMOTE_USER: {{ printf "%s" .Values.jarvice.JARVICE_REMOTE_USER | b64enc }}
  JARVICE_REMOTE_APIKEY: {{ printf "%s" .Values.jarvice.JARVICE_REMOTE_APIKEY | b64enc }}
---
{{- if (not (empty .Values.jarvice_mc_portal.env.JARVICE_PORTAL_MAIL_PASSWORD)) }}
apiVersion: v1
kind: Secret
metadata:
  name: jarvice-mc-portal
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-mc-portal
type: Opaque
data:
  JARVICE_PORTAL_MAIL_PASSWORD: {{ printf "%s" .Values.jarvice_mc_portal.env.JARVICE_PORTAL_MAIL_PASSWORD | b64enc }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: jarvice-db
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-db
type: Opaque
data:
{{- if (not (empty .Values.jarvice.JARVICE_DBPASSWD)) }}
  JARVICE_DBPASSWD: {{ printf "%s" .Values.jarvice.JARVICE_DBPASSWD | b64enc }}
{{- end }}
{{- if (not (empty .Values.jarvice_db.env.MYSQL_ROOT_PASSWORD)) }}
  MYSQL_ROOT_PASSWORD: {{ printf "%s" .Values.jarvice_db.env.MYSQL_ROOT_PASSWORD | b64enc }}
{{- end }}
{{- if (not (empty .Values.jarvice_db.env.MYSQL_PASSWORD)) }}
  MYSQL_PASSWORD: {{ printf "%s" .Values.jarvice_db.env.MYSQL_PASSWORD | b64enc }}
{{- end }}
{{- if (not (empty .Values.jarvice_dal.env.JARVICE_SITE_DBPASSWD)) }}
  JARVICE_SITE_DBPASSWD: {{ printf "%s" .Values.jarvice_dal.env.JARVICE_SITE_DBPASSWD | b64enc }}
{{- end }}
{{- if (not (empty .Values.jarvice_mc_portal.env.JARVICE_PORTAL_DBPASSWD)) }}
  JARVICE_PORTAL_DBPASSWD: {{ printf "%s" .Values.jarvice_mc_portal.env.JARVICE_PORTAL_DBPASSWD | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jarvice-tls
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
type: Opaque
data:
{{- if (not (empty .Values.jarvice.tls.crt)) }}
  tls.crt: {{ .Values.jarvice.tls.crt }}
{{- else }}
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURwVENDQW8yZ0F3SUJBZ0lKQUwyNDNJLzZNaEFQTUEwR0NTcUdTSWIzRFFFQkN3VUFNR2t4Q3pBSkJnTlYKQkFZVEFsVlRNUTR3REFZRFZRUUlEQVZVWlhoaGN6RVBNQTBHQTFVRUJ3d0dSR0ZzYkdGek1ROHdEUVlEVlFRSwpEQVpPYVcxaWFYZ3hEekFOQmdOVkJBc01CbEJQVWxSQlRERVhNQlVHQTFVRUF3d09Ta0ZTVmtsRFJTMVFUMUpVClFVd3dIaGNOTVRjd016SXlNRFl4TmpVNFdoY05NVGN3TkRJeE1EWXhOalU0V2pCcE1Rc3dDUVlEVlFRR0V3SlYKVXpFT01Bd0dBMVVFQ0F3RlZHVjRZWE14RHpBTkJnTlZCQWNNQmtSaGJHeGhjekVQTUEwR0ExVUVDZ3dHVG1sdApZbWw0TVE4d0RRWURWUVFMREFaUVQxSlVRVXd4RnpBVkJnTlZCQU1NRGtwQlVsWkpRMFV0VUU5U1ZFRk1NSUlCCklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF3b2RTTHlpSTZ1RFlZYnZuNHBuUkZjU0kKZ2hwUTUzZXpUZXEyM3FMNWY0ZGhUWk9nUjlHdmNlZnVLMXZ3RnhQYjNiWVB2bjhtODVQZzR2UjM1MzNGM3RLVgpFUkRQYTd5aWRGZWZ1RnVTRm0yUEtlWkoxelRXUm5Ed3VMS0p1cXRQdDlPa1ltdmNBK1NveHhQd0VBa0hHTURRCmxhSEtzU2dGYS9raG1OWi9PUFZZSllHSjlFK25KanNwb0hkR2F1RWFvUnczbVhQWUwrbjVhbTVMQmpFYUhqUnYKSjY2UzRUS0UwbTZrQWh1MXV2WkRKRjVDSXdKSVpRM3lvOWNaYVAxZVRWYUMzcjl5L3V5aWhURHRWVXJaTUpHNwpjVWkyNkhvNGNLYVJVeDg3RU9scnJzK0cvNVJJT3grS3BvaXpuYVFxYzdoTlhmOHJKSDdjcXZvVWJlVUxnd0lECkFRQUJvMUF3VGpBZEJnTlZIUTRFRmdRVVh4bkZRTW1hZFBTTWEwb2FSK0p5NnF0NUxaZ3dId1lEVlIwakJCZ3cKRm9BVVh4bkZRTW1hZFBTTWEwb2FSK0p5NnF0NUxaZ3dEQVlEVlIwVEJBVXdBd0VCL3pBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFvSUNZWHBUVUd0cGlaVy9WeWhJejVuaHp2ei90dHF3WENtSi9hZkc3bU96anZWRzQ1dmIrCm93Q0tNOGlOU3VhZDh1eWdtYnovSG5ZT3ErVzVCSmxZQS8wRnZyeDRPWGl3eVYxSWhxRXJnMVBqRWJxVFJIby8KOUlCSzkxbmc2MkRxSkJyajhORnZVcWJvZmhUY0hvN3BTVktabGt1VUIrY3VWVVBINkhSSHFidHUvR1lBbnlVRwp4R1krSmsvNHZXekppbDIrRENUMkpHOHhLcGxsd2hOcGdXYWhaVDhwQVZCTWE3OXpYUU1qOEpzZFc3VDFZV3BnClpFVTRuNkVoa2FPakVOZDhhSFZMbXpDVTdaMXptY1BSTDYvNEUydFBLVklFaGttZDh4M2h0ZU43N3BTM1pIZFoKMStGNGZ1V2t3UXcwdkpBSTlNdnhiT242STNkOGVuMW5KQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
{{- end }}
{{- if (not (empty .Values.jarvice.tls.key)) }}
  tls.key: {{ .Values.jarvice.tls.key }}
{{- else }}
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRENoMUl2S0lqcTROaGgKdStmaW1kRVZ4SWlDR2xEbmQ3Tk42cmJlb3ZsL2gyRk5rNkJIMGE5eDUrNHJXL0FYRTl2ZHRnKytmeWJ6aytEaQo5SGZuZmNYZTBwVVJFTTlydktKMFY1KzRXNUlXYlk4cDVrblhOTlpHY1BDNHNvbTZxMCszMDZSaWE5d0Q1S2pICkUvQVFDUWNZd05DVm9jcXhLQVZyK1NHWTFuODQ5VmdsZ1luMFQ2Y21PeW1nZDBacTRScWhIRGVaYzlndjZmbHEKYmtzR01Sb2VORzhucnBMaE1vVFNicVFDRzdXNjlrTWtYa0lqQWtobERmS2oxeGxvL1Y1TlZvTGV2M0wrN0tLRgpNTzFWU3Rrd2tidHhTTGJvZWpod3BwRlRIenNRNld1dXo0Yi9sRWc3SDRxbWlMT2RwQ3B6dUUxZC95c2tmdHlxCitoUnQ1UXVEQWdNQkFBRUNnZ0VBRXJiMEdDZGRMTU9lN2FBblNleWthZVN6Z1ZqSXljd0JTeEMyc1NxYXVFTXQKQUVxZ2srZy9hY1QzYStKM2NiRHVhU0VYMktyZzgzUVpvWndGWVJiL2oxVlJGQWc2L0ZGMGk1N1dkZVVSWStqOAphZnFHeGhhR090YW93Z3dqSmZ0UE93ODRkR09PRWkzUWN2NmZETnZoZStjbzZneGJ0TGwxOUJKT3dpWjRyT0Q2CmpGUm5jU3ZZeHJSNSs2YXFoVjRJT0ZneGhZd1hGZWhsZjBrVTNPcU02Y0l2VERJOG5ocXJaYWR0eXFMM2VpV3gKMlVzR0JHTlJkWHlkVVJjWE1NbTlqVWhGOFNrVFNpWGxjbEdEK0lmNXBFUDErQ3FoRC9QbjNNbUlIeTRoQkFjUwpHbC81K2RCOW9xeWJyU1BmSnBTUjdHYSt5cTdyUWwvOENWR3JIcUFjK1FLQmdRRDFrbmNiV0pVc3ZVK0IvV0JkCnRMYkVwYjNqazBxQ3JIMVVRS3FacHVuYUMrcEFKZTEveS9XekZueHF6MUVxUmRNMW1WUVBNU2dnWmt2RWRnSS8KNmU0Uno5VEFrS2NNanhpdUpaRTA5eHlhSjJiNEpSdzdPTVhnYXYvWFN5OE9kQkxmQkZEeFVGZmRDaWJZN2JwegorcG5acWZQSklLUHNoTmhYV1RDY21HM2lkUUtCZ1FES3lmcG5QR0d1cEtNSGZxN2d3SW1HZktGekxVY1I4MWl4ClcxdUFGS0kvY3lueFcwTHQ5VS9zUEE0RXArWXd5WUNhQjJrOHdQNVc1akRmRG0zVVEzVXlvQnVESm5ka1pjcWgKNXBhOE9TYzNCdjJhWjh6Rjl6VUZjdHRGTUNwUE15VlFPeWlkVTRsQzZCN09VUUMvSEduQWh5YnQvZ2NvcFVqTApCYURZKy9LSEZ3S0JnRmM5U3hicDUwVFhsQkZINUI0bC91L3BPWVpKWXlUOUJpRVNRQWtKNVBYVFdjcWtMclZCCnplMXJSWlBrUnA5UDR2S2RuK0V0dzJXUE1jZC9iTmtyejZtQVBjS1RJT1V6U0w5RkZVck5wdG1VdWQzWndTZkEKeVhzcVIrMUNCbHVLSE5JaGhHZlY5UURQaEhGNE1zN1U3aWNIVzFYT1JLM1htOHVjSWNyZjA5bXBBb0dCQUpoSApOYWJpTzhRR1Uzb2tValBwd1J2aGFPZHhmNlhtSTVzRExHR3duT21pbEVOdXNZSzVMS3dMcU1jc1FYb3ZSa2ZqCitzMnBheFJjUlNTcTFDU0tCMjdkdGVzMUxvQ1F3Nm54MncwNnFjenpqZXF0dWFLSzhTREhVQXJUa1dIcDJVSTMKT2xkeHpHZ1dvRk56bG1qc2NDa29GRDZ3L0RVMGNNWXIwczQ5MjdBL0FvR0FBYjE2U05FUEZCbVh6QXhmUTFkZApZdGtqRHFoanIwclBCUG1Qalhkek56TkZyaFBPZUdrdEE3aXloZWM1Mndxdlh6TVZBQzZDVjBwN1hHZGlOdUk3CnN6ckZ4UHBPYmwzb3l6YWVUNy92V0tzTG9KSzF3TGJ6SlNET1dwU29MYmlMVWh1SkZ4bG5zZ08zMVNjcE9YTE4KUDZtZ08wemlVeG5XcVdDY1BDN3k4NU09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jarvice-docker
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.jarvice.JARVICE_SYSTEM_REGISTRY (printf "%s:%s" .Values.jarvice.imagePullSecret.username .Values.jarvice.imagePullSecret.password | b64enc) | b64enc }}
---
{{- if .Values.jarvice_scheduler.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: jarvice-docker
{{- if empty .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
  namespace: {{ .Release.Namespace }}-jobs
{{- else }}
  namespace: {{ .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
{{- end }}
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.jarvice.JARVICE_SYSTEM_REGISTRY (printf "%s:%s" .Values.jarvice.imagePullSecret.username .Values.jarvice.imagePullSecret.password | b64enc) | b64enc }}
---
{{- end }}
{{- if .Values.jarvice_api.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: jarvice-docker
{{- if empty .Values.jarvice.JARVICE_BUILDS_NAMESPACE }}
  namespace: {{ .Release.Namespace }}-builds
{{- else }}
  namespace: {{ .Values.jarvice.JARVICE_BUILDS_NAMESPACE }}
{{- end }}
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.jarvice.JARVICE_SYSTEM_REGISTRY (printf "%s:%s" .Values.jarvice.imagePullSecret.username .Values.jarvice.imagePullSecret.password | b64enc) | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jarvice-docker
{{- if empty .Values.jarvice.JARVICE_PULLS_NAMESPACE }}
  namespace: {{ .Release.Namespace }}-pulls
{{- else }}
  namespace: {{ .Values.jarvice.JARVICE_PULLS_NAMESPACE }}
{{- end }}
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.jarvice.JARVICE_SYSTEM_REGISTRY (printf "%s:%s" .Values.jarvice.imagePullSecret.username .Values.jarvice.imagePullSecret.password | b64enc) | b64enc }}
---
{{- end }}
