{{- if .Values.jarvice_scheduler.enabled }}
apiVersion: v1
kind: Namespace
metadata:
{{- if empty .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
  name: {{ .Release.Namespace }}-jobs
{{- else }}
  name: {{ .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
{{- end }}
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
---
{{- end }}
{{- if .Values.jarvice_api.enabled }}
apiVersion: v1
kind: Namespace
metadata:
{{- if empty .Values.jarvice.JARVICE_BUILDS_NAMESPACE }}
  name: {{ .Release.Namespace }}-builds
{{- else }}
  name: {{ .Values.jarvice.JARVICE_BUILDS_NAMESPACE }}
{{- end }}
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
---
apiVersion: v1
kind: Namespace
metadata:
{{- if empty .Values.jarvice.JARVICE_PULLS_NAMESPACE }}
  name: {{ .Release.Namespace }}-pulls
{{- else }}
  name: {{ .Values.jarvice.JARVICE_PULLS_NAMESPACE }}
{{- end }}
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
---
{{- end }}
