{{- if .Values.jarvice_k8s_scheduler.enabled }}
{{- if gt (.Values.jarvice_k8s_scheduler.replicaCount | int) 1 }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: jarvice-k8s-scheduler
spec:
  selector:
    matchLabels:
      deployment: jarvice-k8s-scheduler
  minAvailable: {{ .Values.jarvice_k8s_scheduler.pdb.minAvailable }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvice-k8s-scheduler
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-k8s-scheduler
    deployment: jarvice-k8s-scheduler
    jarvice-system: core
spec:
  replicas: {{ .Values.jarvice_k8s_scheduler.replicaCount }}
  selector:
    matchLabels:
      deployment: jarvice-k8s-scheduler
  template:
    metadata:
      labels:
        {{- include "jarvice.release_labels" . | indent 8 }}
        component: jarvice-k8s-scheduler
        deployment: jarvice-k8s-scheduler
        jarvice-system: core
      annotations:
        deployment-date: {{ now | quote }}
    spec:
      serviceAccountName: jarvice-system
{{- if (not (empty .Values.jarvice_k8s_scheduler.tolerations)) }}
      tolerations: {{ .Values.jarvice_k8s_scheduler.tolerations }}
{{- else if (not (empty .Values.jarvice.tolerations)) }}
      tolerations: {{ .Values.jarvice.tolerations }}
{{- end }}
{{- if (not (empty .Values.jarvice_k8s_scheduler.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice_k8s_scheduler.nodeSelector }}
{{- else if (not (empty .Values.jarvice.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice.nodeSelector }}
{{- end }}
      affinity:
        podAntiAffinity:
        {{- if eq .Values.jarvice_k8s_scheduler.antiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                deployment: jarvice-k8s-scheduler
        {{- else if eq .Values.jarvice_k8s_scheduler.antiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  deployment: jarvice-k8s-scheduler
        {{- end }}
      imagePullSecrets:
      - name: jarvice-docker
      containers:
      - name: jarvice-k8s-scheduler
        image: {{ .Values.jarvice.JARVICE_SYSTEM_REGISTRY }}/{{ .Values.jarvice.JARVICE_SYSTEM_REPO_BASE }}/jarvice-k8s-scheduler:{{ default .Values.jarvice.JARVICE_IMAGES_TAG .Chart.Annotations.tag }}{{- include "jarvice.version" . }}
{{- if and (empty .Values.jarvice.JARVICE_IMAGES_VERSION) (empty .Chart.Annotations.tag) }}
        imagePullPolicy: Always
{{- else }}
        imagePullPolicy: IfNotPresent
{{- end }}
        ports:
          - name: http
            containerPort: 8080
        readinessProbe:
          httpGet:
            scheme: HTTP
            port: http
            path: /ready
          initialDelaySeconds: {{ .Values.jarvice_k8s_scheduler.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.jarvice_k8s_scheduler.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.jarvice_k8s_scheduler.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.jarvice_k8s_scheduler.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.jarvice_k8s_scheduler.readinessProbe.failureThreshold }}
        livenessProbe:
          httpGet:
            scheme: HTTP
            port: http
            path: /live
          initialDelaySeconds: {{ .Values.jarvice_k8s_scheduler.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.jarvice_k8s_scheduler.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.jarvice_k8s_scheduler.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.jarvice_k8s_scheduler.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.jarvice_k8s_scheduler.livenessProbe.failureThreshold }}
        env:
          - name: JARVICE_SYSTEM_K8S
{{- if empty .Values.jarvice.JARVICE_SYSTEM_K8S }}
            value: "true"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_SYSTEM_K8S }}"
{{- end }}
          - name: JARVICE_EXPERIMENTAL
{{- if empty .Values.jarvice.JARVICE_EXPERIMENTAL }}
            value: "false"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_EXPERIMENTAL }}"
{{- end }}
          - name: JARVICE_CLUSTER_TYPE
{{- if empty .Values.jarvice.JARVICE_CLUSTER_TYPE }}
            value: "upstream"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_CLUSTER_TYPE }}"
{{- end }}
{{- if (not (eq "downstream" .Values.jarvice.JARVICE_CLUSTER_TYPE)) }}
          - name: JARVICE_DAL_URL
            value: "http://jarvice-dal:8080"
          - name: JARVICE_SCHED_URL
            value: "https://jarvice-scheduler:9443"
{{- end }}
          - name: JARVICE_SCHED_SERVER_KEY
            valueFrom:
              secretKeyRef:
                name: jarvice-sched-server-key
                key: JARVICE_SCHED_SERVER_KEY
                optional: true
          - name: JARVICE_JOBS_NAMESPACE
{{- if empty .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
            value: {{ .Release.Namespace }}-jobs
{{- else }}
            value: {{ .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
{{- end }}
          - name: JARVICE_SYSTEM_NAMESPACE
{{- if empty .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
            value: {{ .Release.Namespace }}
{{- else }}
            value: {{ .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
{{- end }}
          - name: JARVICE_SYSTEM_REGISTRY
            value: {{ .Values.jarvice.JARVICE_SYSTEM_REGISTRY }}
          - name: JARVICE_SYSTEM_REPO_BASE
            value: {{ .Values.jarvice.JARVICE_SYSTEM_REPO_BASE }}
          - name: JARVICE_IMAGES_TAG
            value: {{ default .Values.jarvice.JARVICE_IMAGES_TAG .Chart.Annotations.tag }}{{- include "jarvice.version" . }}
          - name: JARVICE_LOCAL_REGISTRY
            value: {{ .Values.jarvice.JARVICE_LOCAL_REGISTRY }}
          - name: JARVICE_LOCAL_REPO_BASE
            value: {{ .Values.jarvice.JARVICE_LOCAL_REPO_BASE }}
          - name: JARVICE_K8S_ADMIN_CONF
            value: "{{ .Values.jarvice_k8s_scheduler.env.JARVICE_K8S_ADMIN_CONF }}"
          - name: JARVICE_SCHED_PLUGIN_USE
            value: "true"
          - name: JARVICE_UNFS_REQUEST_MEM
{{- if (not (empty .Values.jarvice_scheduler.env.JARVICE_UNFS_REQUEST_MEM)) }}
            value: "{{ .Values.jarvice_scheduler.env.JARVICE_UNFS_REQUEST_MEM }}"
{{- else }}
            value: "{{ .Values.jarvice_k8s_scheduler.env.JARVICE_UNFS_REQUEST_MEM }}"
{{- end }}
          - name: JARVICE_UNFS_REQUEST_CPU
{{- if (not (empty .Values.jarvice_scheduler.env.JARVICE_UNFS_REQUEST_CPU)) }}
            value: "{{ .Values.jarvice_scheduler.env.JARVICE_UNFS_REQUEST_CPU }}"
{{- else }}
            value: "{{ .Values.jarvice_k8s_scheduler.env.JARVICE_UNFS_REQUEST_CPU }}"
{{- end }}
          - name: JARVICE_UNFS_EXPIRE_SECS
{{- if (not (empty .Values.jarvice_scheduler.env.JARVICE_UNFS_EXPIRE_SECS)) }}
            value: "{{ .Values.jarvice_scheduler.env.JARVICE_UNFS_EXPIRE_SECS }}"
{{- else }}
            value: "{{ .Values.jarvice_k8s_scheduler.env.JARVICE_UNFS_EXPIRE_SECS }}"
{{- end }}
{{- if (not (empty .Values.jarvice_scheduler.env.JARVICE_UNFS_NODE_SELECTOR)) }}
          - name: JARVICE_UNFS_NODE_SELECTOR
            value: '{{ .Values.jarvice_scheduler.env.JARVICE_UNFS_NODE_SELECTOR }}'
{{- else if (not (empty .Values.jarvice_k8s_scheduler.env.JARVICE_UNFS_NODE_SELECTOR)) }}
          - name: JARVICE_UNFS_NODE_SELECTOR
            value: '{{ .Values.jarvice_k8s_scheduler.env.JARVICE_UNFS_NODE_SELECTOR }}'
{{- else if (not (empty .Values.jarvice_dal.nodeSelector)) }}
          - name: JARVICE_UNFS_NODE_SELECTOR
            value: '{{ .Values.jarvice_dal.nodeSelector }}'
{{- else if (not (empty .Values.jarvice.nodeSelector)) }}
          - name: JARVICE_UNFS_NODE_SELECTOR
            value: '{{ .Values.jarvice.nodeSelector }}'
{{- end }}
{{- if .Values.jarvice_pod_scheduler.enabled }}
          - name: JARVICE_POD_SCHED_USE
{{- if empty .Values.jarvice_pod_scheduler.JARVICE_POD_SCHED_NAME }}
            value: "{{ .Release.Namespace }}"
{{- else }}
            value: "{{ .Values.jarvice_pod_scheduler.env.JARVICE_POD_SCHED_NAME }}"
{{- end }}
{{- end }}
{{- if (not (empty .Values.jarvice_k8s_scheduler.env.JARVICE_UNFS3_IMAGE)) }}
          - name: JARVICE_UNFS3_IMAGE
            value: '{{ .Values.jarvice_k8s_scheduler.env.JARVICE_UNFS3_IMAGE }}'
{{- end }}
{{- if (not (empty .Values.jarvice_k8s_scheduler.env.JARVICE_PVCLS_IMAGE)) }}
          - name: JARVICE_PVCLS_IMAGE
            value: '{{ .Values.jarvice_k8s_scheduler.env.JARVICE_PVCLS_IMAGE }}'
{{- end }}
{{- if (not (empty .Values.jarvice_k8s_scheduler.env.JARVICE_SCHED_JOB_UID)) }}
          - name: JARVICE_SCHED_JOB_UID
            value: "{{ .Values.jarvice_k8s_scheduler.env.JARVICE_SCHED_JOB_UID }}"
{{- end }}
{{- if (not (empty .Values.jarvice_k8s_scheduler.env.JARVICE_SCHED_JOB_GID)) }}
          - name: JARVICE_SCHED_JOB_GID
            value: "{{ .Values.jarvice_k8s_scheduler.env.JARVICE_SCHED_JOB_GID }}"
{{- end }}
          - name: JARVICE_JOBS_DOMAIN
            value: "{{ .Values.jarvice.JARVICE_JOBS_DOMAIN }}"
          - name: JARVICE_JOBS_LB_SERVICE
            value: "{{ .Values.jarvice.JARVICE_JOBS_LB_SERVICE }}"
          - name: JARVICE_JOBS_LB_ANNOTATIONS
            value: '{{ .Values.jarvice.JARVICE_JOBS_LB_ANNOTATIONS }}'
          - name: JARVICE_JOBS_MULTI_TENANT
            value: "{{ .Values.jarvice.JARVICE_JOBS_MULTI_TENANT }}"
          - name: JARVICE_JOBS_MULTI_TENANT_INGRESS_POD_LABELS
            value: '{{ .Values.jarvice.JARVICE_JOBS_MULTI_TENANT_INGRESS_POD_LABELS }}'
          - name: JARVICE_JOBS_MULTI_TENANT_INGRESS_NS_LABELS
            value: '{{ .Values.jarvice.JARVICE_JOBS_MULTI_TENANT_INGRESS_NS_LABELS }}'
          - name: JARVICE_JOBS_MULTI_TENANT_LB_SERVICE_CIDRS
            value: '{{ .Values.jarvice.JARVICE_JOBS_MULTI_TENANT_LB_SERVICE_CIDRS }}'
          - name: JARVICE_JOBS_INIT_IMAGE_PULL_POLICY
{{- if and (empty .Values.jarvice.JARVICE_IMAGES_VERSION) (empty .Chart.Annotations.tag) }}
            value: "Always"
{{- else }}
            value: "IfNotPresent"
{{- end }}
          - name: JARVICE_JOBS_IMAGE_PULL_POLICY
            value: "{{ .Values.jarvice.JARVICE_JOBS_IMAGE_PULL_POLICY }}"
          - name: JARVICE_K8S_SCHED_LOGLEVEL
            value: "{{ .Values.jarvice.JARVICE_K8S_SCHED_LOGLEVEL }}"
          - name: JARVICE_SELINUX_ENFORCING
{{- if empty .Values.jarvice.JARVICE_SELINUX_ENFORCING }}
            value: "false"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_SELINUX_ENFORCING }}"
{{- end }}
        resources:
{{- if .Values.jarvice_k8s_scheduler.resources }}
{{ toYaml .Values.jarvice_k8s_scheduler.resources | indent 10 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: jarvice-k8s-scheduler
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-k8s-scheduler
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  selector:
    deployment: jarvice-k8s-scheduler
---
{{- if or .Values.jarvice_k8s_scheduler.networkPolicy.enabled (and (eq "<nil>" (toString .Values.jarvice_k8s_scheduler.networkPolicy.enabled)) .Values.jarvice.networkPolicy.enabled) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jarvice-k8s-scheduler
spec:
  podSelector:
    matchLabels:
      deployment: jarvice-k8s-scheduler
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Release.Namespace }}
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8080
{{- if (eq "downstream" .Values.jarvice.JARVICE_CLUSTER_TYPE) }}
{{- if (empty .Values.jarvice_k8s_scheduler.ingressHost) }}
  - {}
{{- else }}
  - from:
    - namespaceSelector: {}
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8080
{{- end }}
{{- end }}
---
{{- end }}
{{- if (eq "downstream" .Values.jarvice.JARVICE_CLUSTER_TYPE) }}
{{- if (empty .Values.jarvice_k8s_scheduler.ingressHost) }}
apiVersion: v1
kind: Service
metadata:
  name: jarvice-k8s-scheduler-lb
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-k8s-scheduler
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.jarvice_k8s_scheduler.loadBalancerIP }}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  selector:
    deployment: jarvice-k8s-scheduler
---
{{- else }}
apiVersion: {{ template "apiVersion.ingress" . }}
kind: Ingress
metadata:
  name: jarvice-k8s-scheduler
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-k8s-scheduler
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: jarvice-k8s-scheduler
          servicePort: http
{{- if ne "-" .Values.jarvice_k8s_scheduler.ingressHost }}
{{- if eq "lookup" .Values.jarvice_k8s_scheduler.ingressHost }}
    host: '{{- (first (lookup "v1" "Service" .Values.jarvice_k8s_scheduler.ingressServiceNamespace .Values.jarvice_k8s_scheduler.ingressService).status.loadBalancer.ingress).hostname }}'
{{- else }}
    host: {{ .Values.jarvice_k8s_scheduler.ingressHost }}
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
