{{- if .Values.jarvice_mc_portal.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: jarvice-mc-portal
spec:
  selector:
    matchLabels:
      deployment: jarvice-mc-portal
  minAvailable: {{ .Values.jarvice_mc_portal.pdb.minAvailable }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvice-mc-portal
spec:
  replicas: {{ .Values.jarvice_mc_portal.replicaCount }}
  selector:
    matchLabels:
      deployment: jarvice-mc-portal
  template:
    metadata:
      labels:
        {{- include "jarvice.release_labels" . | indent 8 }}
        component: jarvice-mc-portal
        deployment: jarvice-mc-portal
      annotations:
        deployment-date: {{ now | quote }}
    spec:
{{- if (not (empty .Values.jarvice_mc_portal.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice_mc_portal.nodeSelector }}
{{- else if (not (empty .Values.jarvice.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice.nodeSelector }}
{{- end }}
      affinity:
        podAntiAffinity:
        {{- if eq .Values.jarvice_mc_portal.antiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                deployment: jarvice-mc-portal
        {{- else if eq .Values.jarvice_mc_portal.antiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  deployment: jarvice-mc-portal
        {{- end }}
      imagePullSecrets:
      - name: jarvice-docker
      volumes:
        - name: jarvice-settings
          configMap:
            name: {{ .Values.jarvice.settings.configMap }}
            optional: true
        - name: jarvice-secrets
          secret:
            secretName: {{ .Values.jarvice.secrets.secretName }}
            optional: true
      containers:
      - name: jarvice-mc-portal
        image: {{ .Values.jarvice.JARVICE_SYSTEM_REGISTRY }}/{{ .Values.jarvice.JARVICE_SYSTEM_REPO_BASE }}/jarvice-mc-portal:{{ .Values.jarvice.JARVICE_IMAGES_TAG }}-{{ .Values.jarvice.JARVICE_SYSTEM_ARCH }}
        imagePullPolicy: Always
        ports:
          - name: https
            containerPort: 443
          - name: http
            containerPort: 80
        readinessProbe:
          httpGet:
            scheme: HTTPS
            port: https
            path: /ready
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            scheme: HTTPS
            port: https
            path: /live
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        env:
          - name: JARVICE_MC_PORTAL_HTTPS
            value: "enable"
          - name: JARVICE_MC_PORTAL_HTTPS_PORT
            value: "443"
          - name: JARVICE_MC_PORTAL_HTTP
            value: "enable"
          - name: JARVICE_MC_PORTAL_HTTP_PORT
            value: "80"
          #- name: JARVICE_MC_PORTAL_HTTP_REDIRECT_PORT
          #  value: "443"
          - name: JARVICE_DAL_URL
            value: "https://jarvice-dal:8443"
          - name: JARVICE_API_URL
            value: "https://jarvice-api:7443"
          - name: JARVICE_MC_PORTAL_CRT
            value: {{ toYaml .Values.jarvice_mc_portal.env.JARVICE_MC_PORTAL_CRT | indent 12 }}
          - name: JARVICE_MC_PORTAL_KEY
            value: {{ toYaml .Values.jarvice_mc_portal.env.JARVICE_MC_PORTAL_KEY | indent 12 }}
          - name: JARVICE_USER_DEFAULT_ENABLED
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_USER_DEFAULT_ENABLED }}"
          - name: JARVICE_USER_DEFAULT_DEVELOPER
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_USER_DEFAULT_DEVELOPER }}"
          - name: JARVICE_PORTAL_WEB_HOST
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_WEB_HOST }}"
          - name: JARVICE_PORTAL_MEMCACHED_LOCATIONS
{{- if and .Values.jarvice_memcached.enabled (empty .Values.jarvice_mc_portal.env.JARVICE_PORTAL_MEMCACHED_LOCATIONS) }}
            {{- $memcachedCount := .Values.jarvice_memcached.replicaCount }}
            value: "
              {{- range $i, $none := until (int $memcachedCount) }}
                {{- if gt $i 0}},{{- end }}jarvice-memcached-{{ $i }}.jarvice-memcached:11211
              {{- end }}"
{{- else }}
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_MEMCACHED_LOCATIONS }}"
{{- end }}
          - name: JARVICE_PORTAL_APP_OWNERS
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_APP_OWNERS }}"
          - name: JARVICE_PORTAL_MAIL_FROM
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_MAIL_FROM }}"
          - name: JARVICE_PORTAL_MAIL_SUBJECT
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_MAIL_SUBJECT }}"
          - name: JARVICE_PORTAL_MAIL_SERVER
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_MAIL_SERVER }}"
          - name: JARVICE_PORTAL_MAIL_USERNAME
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_MAIL_USERNAME }}"
          - name: JARVICE_PORTAL_MAIL_PASSWORD
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_MAIL_PASSWORD }}"
          - name: JARVICE_PORTAL_MAIL_ADMINS
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_MAIL_ADMINS }}"
          - name: JARVICE_PORTAL_DBHOST
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_DBHOST }}"
          - name: JARVICE_PORTAL_DBUSER
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_DBUSER }}"
          - name: JARVICE_PORTAL_DBPASSWD
{{- if empty .Values.jarvice_mc_portal.env.JARVICE_PORTAL_DBPASSWD }}
            value: "{{ .Values.jarvice_db.env.MYSQL_ROOT_PASSWORD }}"
{{- else }}
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_DBPASSWD }}"
{{- end }}
        volumeMounts:
        - name: jarvice-settings
          mountPath: /etc/jarvice/settings/jarvice-mc-portal
          readOnly: true
        - name: jarvice-secrets
          mountPath: /etc/jarvice/secrets/jarvice-mc-portal
          readOnly: true
        resources:
{{- if .Values.jarvice_mc_portal.resources }}
{{ toYaml .Values.jarvice_mc_portal.resources | indent 10 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: jarvice-mc-portal
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-mc-portal
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
    name: https
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  selector:
    deployment: jarvice-mc-portal
---
apiVersion: v1
kind: Service
metadata:
  name: jarvice-mc-portal-lb
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-mc-portal
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.jarvice_mc_portal.loadBalancerIP }}
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
    name: https
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  selector:
    deployment: jarvice-mc-portal
---
{{- if (not (empty .Values.jarvice_mc_portal.ingressHost)) }}
apiVersion: v1
kind: Secret
metadata:
  name: jarvice-mc-portal-tls
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-mc-portal
type: Opaque
data:
  tls.crt: {{ .Values.jarvice_mc_portal.secret.crt }}
  tls.key: {{ .Values.jarvice_mc_portal.secret.key }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jarvice-mc-portal
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-mc-portal
  annotations:
    ingress.kubernetes.io/ssl-passthrough: "true"
    #ingress.kubernetes.io/ssl-redirect: "true"
    #ingress.kubernetes.io/affinity: cookie
    #ingress.kubernetes.io/cache-enable: "false"
    #ingress.kubernetes.io/cache-ignore-cookies: '*'
spec:
  #tls:
  #- hosts:
  #  - {{ .Values.jarvice_mc_portal.ingressHost }}
  #  secretName: jarvice-mc-portal-tls
  rules:
  - host: {{ .Values.jarvice_mc_portal.ingressHost }}
    http:
      paths:
      - backend:
          serviceName: jarvice-mc-portal
          servicePort: https
---
{{- end }}
{{- end }}
