{{- if .Values.jarvice_scheduler.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: jarvice-scheduler
spec:
  selector:
    matchLabels:
      deployment: jarvice-scheduler
  minAvailable: {{ .Values.jarvice_scheduler.pdb.minAvailable }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvice-scheduler
spec:
  replicas: {{ .Values.jarvice_scheduler.replicaCount }}
  selector:
    matchLabels:
      deployment: jarvice-scheduler
  template:
    metadata:
      labels:
        {{- include "jarvice.release_labels" . | indent 8 }}
        component: jarvice-scheduler
        deployment: jarvice-scheduler
      annotations:
        deployment-date: {{ now | quote }}
    spec:
      serviceAccountName: jarvice-system
{{- if (not (empty .Values.jarvice_scheduler.tolerations)) }}
      tolerations: {{ .Values.jarvice_scheduler.tolerations }}
{{- else if (not (empty .Values.jarvice.tolerations)) }}
      tolerations: {{ .Values.jarvice.tolerations }}
{{- end }}
{{- if (not (empty .Values.jarvice_scheduler.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice_scheduler.nodeSelector }}
{{- else if (not (empty .Values.jarvice.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice.nodeSelector }}
{{- end }}
      affinity:
        podAntiAffinity:
        {{- if eq .Values.jarvice_scheduler.antiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                deployment: jarvice-scheduler
        {{- else if eq .Values.jarvice_scheduler.antiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  deployment: jarvice-scheduler
        {{- end }}
      imagePullSecrets:
      - name: jarvice-docker
      volumes:
        - name: jarvice-settings
          configMap:
            name: {{ .Values.jarvice.settings.configMap }}
            optional: true
      containers:
      - name: jarvice-scheduler
        image: {{ .Values.jarvice.JARVICE_SYSTEM_REGISTRY }}/{{ .Values.jarvice.JARVICE_SYSTEM_REPO_BASE }}/jarvice-scheduler:{{ .Values.jarvice.JARVICE_IMAGES_TAG }}{{- include "jarvice.version" . -}}
        imagePullPolicy: Always
        ports:
          - name: https
            containerPort: 9443
        readinessProbe:
          httpGet:
            scheme: HTTPS
            port: https
            path: /ready
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            scheme: HTTPS
            port: https
            path: /live
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        env:
          - name: JARVICE_SYSTEM_K8S
            value: "true"
          - name: JARVICE_DAL_URL
            value: "https://jarvice-dal:8443"
          - name: JARVICE_SCHED_URL
            value: "https://jarvice-scheduler:9443"
          - name: JARVICE_LICENSE_LIC
            valueFrom:
              secretKeyRef:
                name: jarvice-license
                key: JARVICE_LICENSE_LIC
          - name: JARVICE_JOBS_NAMESPACE
{{- if empty .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
            value: {{ .Release.Namespace }}-jobs
{{- else }}
            value: {{ .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
{{- end }}
          - name: JARVICE_SYSTEM_NAMESPACE
{{- if empty .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
            value: {{ .Release.Namespace }}
{{- else }}
            value: {{ .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
{{- end }}
          - name: JARVICE_SYSTEM_REGISTRY
            value: {{ .Values.jarvice.JARVICE_SYSTEM_REGISTRY }}
          - name: JARVICE_SYSTEM_REPO_BASE
            value: {{ .Values.jarvice.JARVICE_SYSTEM_REPO_BASE }}
          - name: JARVICE_IMAGES_TAG
            value: {{ .Values.jarvice.JARVICE_IMAGES_TAG }}{{- include "jarvice.version" . -}}
          - name: JARVICE_LOCAL_REGISTRY
            value: {{ .Values.jarvice.JARVICE_LOCAL_REGISTRY }}
          - name: JARVICE_LOCAL_REPO_BASE
            value: {{ .Values.jarvice.JARVICE_LOCAL_REPO_BASE }}
          - name: JARVICE_USE_LXCFS
            value: "{{ .Values.jarvice_scheduler.env.JARVICE_USE_LXCFS }}"
          - name: JARVICE_K8S_ADMIN_CONF
            value: "{{ .Values.jarvice_scheduler.env.JARVICE_K8S_ADMIN_CONF }}"
          - name: JARVICE_SCHED_PASS_INTERVAL
            value: "{{ .Values.jarvice_scheduler.env.JARVICE_SCHED_PASS_INTERVAL }}"
          - name: JARVICE_UNFS_REQUEST_MEM
            value: "{{ .Values.jarvice_scheduler.env.JARVICE_UNFS_REQUEST_MEM }}"
          - name: JARVICE_UNFS_REQUEST_CPU
            value: "{{ .Values.jarvice_scheduler.env.JARVICE_UNFS_REQUEST_CPU }}"
{{- if (not (empty .Values.jarvice_scheduler.JARVICE_UNFS_NODE_SELECTOR)) }}
          - name: JARVICE_UNFS_NODE_SELECTOR
            value: '{{ .Values.jarvice_scheduler.JARVICE_UNFS_NODE_SELECTOR }}'
{{- else if (not (empty .Values.jarvice_dal.nodeSelector)) }}
          - name: JARVICE_UNFS_NODE_SELECTOR
            value: '{{ .Values.jarvice_dal.nodeSelector }}'
{{- else if (not (empty .Values.jarvice.nodeSelector)) }}
          - name: JARVICE_UNFS_NODE_SELECTOR
            value: '{{ .Values.jarvice.nodeSelector }}'
{{- end }}
{{- if .Values.jarvice_pod_scheduler.enabled }}
          - name: JARVICE_POD_SCHED_USE
{{- if empty .Values.jarvice_pod_scheduler.JARVICE_POD_SCHED_NAME }}
            value: "{{ .Release.Namespace }}"
{{- else }}
            value: "{{ .Values.jarvice_pod_scheduler.env.JARVICE_POD_SCHED_NAME }}"
{{- end }}
{{- end }}
          - name: JARVICE_JOBS_DOMAIN
            value: "{{ .Values.jarvice.JARVICE_JOBS_DOMAIN }}"
          - name: JARVICE_JOBS_LB_SERVICE
            value: "{{ .Values.jarvice.JARVICE_JOBS_LB_SERVICE }}"
          - name: JARVICE_MAIL_CONF
{{- if empty .Values.jarvice_scheduler.env.JARVICE_MAIL_CONF }}
            value: {{ toYaml .Values.jarvice.JARVICE_MAIL_CONF | indent 12 }}
{{- else }}
            value: {{ toYaml .Values.jarvice_scheduler.env.JARVICE_MAIL_CONF | indent 12 }}
{{- end }}
        volumeMounts:
        - name: jarvice-settings
          mountPath: /etc/jarvice/settings/jarvice-scheduler
          readOnly: true
        resources:
{{- if .Values.jarvice_scheduler.resources }}
{{ toYaml .Values.jarvice_scheduler.resources | indent 10 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: jarvice-scheduler
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-scheduler
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9443
    targetPort: 9443
    name: https
  selector:
    deployment: jarvice-scheduler
---
{{- end }}
