{{- if .Values.jarvice_scheduler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvice-scheduler
spec:
  replicas: {{ .Values.jarvice_scheduler.replicaCount }}
  selector:
    matchLabels:
      deployment: jarvice-scheduler
  template:
    metadata:
      labels:
        {{- include "jarvice.release_labels" . | indent 8 }}
        component: jarvice-scheduler
        deployment: jarvice-scheduler
    spec:
      serviceAccountName: {{ .Values.jarvice.kubernetes.serviceAccount }}
      nodeSelector:
        beta.kubernetes.io/arch: "{{ .Values.jarvice.JARVICE_SYSTEM_ARCH }}"
{{- if .Values.jarvice_scheduler.nodeSelector }}
{{ toYaml .Values.jarvice_scheduler.nodeSelector | indent 8 }}
{{- end }}
      imagePullSecrets:
      - name: jarvice-docker
      volumes:
        - name: jarvice-settings
          configMap:
            name: {{ .Values.jarvice.settings.configMap }}
            optional: true
      containers:
      - name: jarvice-scheduler
        image: {{ .Values.jarvice.JARVICE_SYSTEM_REGISTRY }}/{{ .Values.jarvice.JARVICE_SYSTEM_REPO_BASE }}/jarvice-scheduler:{{ .Values.jarvice.JARVICE_IMAGES_TAG }}-{{ .Values.jarvice.JARVICE_SYSTEM_ARCH }}{{ .Values.jarvice.JARVICE_IMAGES_TAG_DEV }}
        imagePullPolicy: Always
        ports:
          - name: https
            containerPort: 9443
        readinessProbe:
          tcpSocket:
            scheme: HTTPS
            port: https
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            scheme: HTTPS
            port: https
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        env:
          - name: JARVICE_DAL_URL
            value: "https://jarvice-dal:8443"
          - name: JARVICE_LICENSE_LIC
            value: {{ .Values.jarvice.JARVICE_LICENSE_LIC }}
          - name: JARVICE_JOBS_NAMESPACE
            value: {{ .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
          - name: JARVICE_SYSTEM_NAMESPACE
            value: {{ .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
          - name: JARVICE_SYSTEM_REGISTRY
            value: {{ .Values.jarvice.JARVICE_SYSTEM_REGISTRY }}
          - name: JARVICE_SYSTEM_REPO_BASE
            value: {{ .Values.jarvice.JARVICE_SYSTEM_REPO_BASE }}
          - name: JARVICE_IMAGES_TAG
            value: {{ .Values.jarvice.JARVICE_IMAGES_TAG }}
          - name: JARVICE_LOCAL_REGISTRY
            value: {{ .Values.jarvice.JARVICE_LOCAL_REGISTRY }}
          - name: JARVICE_LOCAL_REPO_BASE
            value: {{ .Values.jarvice.JARVICE_LOCAL_REPO_BASE }}
          - name: JARVICE_USE_LXCFS
            value: "{{ .Values.jarvice_scheduler.env.JARVICE_USE_LXCFS }}"
          - name: JARVICE_K8S_ADMIN_CONF
            value: "{{ .Values.jarvice_scheduler.env.JARVICE_K8S_ADMIN_CONF }}"
          - name: JARVICE_SCHED_PASS_INTERVAL
            value: "{{ .Values.jarvice_scheduler.env.JARVICE_SCHED_PASS_INTERVAL }}"
          - name: JARVICE_MAIL_CONF
            value: {{ toYaml .Values.jarvice_scheduler.env.JARVICE_MAIL_CONF | indent 12 }}
        volumeMounts:
        - name: jarvice-settings
          mountPath: /etc/jarvice/jarvice-scheduler
          readOnly: true
        resources:
{{- if .Values.jarvice_scheduler.resources }}
{{ toYaml .Values.jarvice_scheduler.resources | indent 10 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: jarvice-scheduler
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-scheduler
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9443
    targetPort: 9443
    name: https
  selector:
    deployment: jarvice-scheduler
---
{{- end }}
