---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: jarvice-api-lb
  labels:
    app: {{ template "jarvice.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-install
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 443
    targetPort: 7443
    name: https
  - protocol: TCP
    port: 80
    targetPort: 7080
    name: http
  selector:
    deployment: jarvice-api
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: jarvice-mc-portal-lb
  labels:
    app: {{ template "jarvice.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-install
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
    name: https
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  selector:
    deployment: jarvice-mc-portal
---
{{- if eq true .Values.jarvice_registry.enabled -}}
{{- if eq true .Values.jarvice_registry.external -}}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "jarvice.name" . }}-registry-lb
  labels:
    app: {{ template "jarvice.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-install
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    name: http
#  - protocol: TCP
#    port: 443
#    targetPort: 443
#    name: https
#  - protocol: TCP
#    port: 80
#    targetPort: 80
#    name: http
  selector:
    deployment: {{ template "jarvice.name" . }}-registry
---
{{- end }}
{{- end }}
