apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
  #annotations:
  #  "helm.sh/hook": pre-install
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jarvice-system
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
  annotations:
    "helm.sh/hook": pre-install
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jarvice-system-{{ .Release.Name }}
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
  #name: {{ .Values.jarvice.kubernetes.clusterRole }}
subjects:
- kind: ServiceAccount
  name: jarvice-system
  namespace: {{ .Release.Namespace }}
---
{{- if .Values.jarvice.kubernetes.createClusterRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.jarvice.kubernetes.clusterRole }}
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
  annotations:
    "helm.sh/hook": pre-install
    #"helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["services/proxy"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
- apiGroups: ["extensions"]
  resources: ["networkpolicies"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
---
{{- end }}
